### Dispatch Notification Message
POST http://localhost:3000/notifications
Content-Type: application/json

{
  "message": "Heey there!!!"
}

### Flush Notifications From Dead Letter Queue
POST http://localhost:3000/notifications/flush-from-deadletter
Content-Type: application/json

{}

### Get processed notifications
GET http://localhost:3001/processed-messages
Content-Type: application/json