### Create Blue Book Entry
POST http://localhost:3000/blue-book-entries
Content-Type: application/json

{
  "title": "Heey there",
  "body": "This is notification message.",
  "from_name": "Joana",
  "to_name": "Agatha"
}

### Read all Blue Book Entries
GET http://localhost:3000/blue-book-entries
Content-Type: application/json

{
  "title": "Heey there",
  "body": "This is notification message.",
  "from_name": "Joana",
  "to_name": "Agatha"
}

### Flush Notifications From Dead Letter Queue
POST http://localhost:3000/messages/flush-from-deadletter
Content-Type: application/json

{}

### Get processed notifications
GET http://localhost:3001/processed-messages
Content-Type: application/json