FROM node:20-alpine as development_dependencies
WORKDIR /app
COPY package.json ./
RUN npm install

FROM node:20-alpine as development
WORKDIR /app
COPY --from=development_dependencies /app/node_modules ./node_modules

EXPOSE 3000

CMD ["npm", "run", "start:dev"]