FROM node:20-alpine AS development_dependencies
WORKDIR /app
COPY package.json ./
RUN npm install

FROM node:20-alpine AS development
WORKDIR /app
COPY --from=development_dependencies /app/node_modules ./node_modules
COPY package.json ./
COPY src ./src
COPY tsconfig.json ./

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
